lasdi:
  type:                     gplasdi
  gplasdi:
    lr:                     0.001
    n_samples:              20

    # Note that t_rollout is capped at 0.75 to ensure there are some frames to simulate forward.
    p_rollout_init:         0.01
    rollout_update_freq:    100
    dp_per_update:          0.002

    max_iter:               1000
    n_iter:                 300
    max_greedy_iter:        1000

    loss_weights:
      recon:                1.0
      chain_rule:           1.0
      LD:                   0.5
      rollout:              0.5
      coef:                 0.0001
      consistency:          1.0

workflow:
  use_restart:              false
  restart_file:             restarts/burgers1d.restart.npy

parameter_space:
  parameters:
    - name:                 s
      min:                  0.0008
      max:                  0.0016
      test_space_type:      uniform
      sample_size:          5
      log_scale:            false
    - name:                 K
      min:                  4.0
      max:                  6.0
      test_space_type:      uniform
      sample_size:          5
      log_scale:            false
  test_space:
    type:                   grid

model:
  type:                     pair
  pair:
    hidden_widths:          [250, 100, 100, 100]
    latent_dimension:       5  

latent_dynamics:
  type:                     spring
  coef_norm_order:          fro
  spring:

physics:
  type:                     NonlinearElasticity
  NonlinearElasticity:


