trainer:
  type:                     "First_Order_Weak"

  max_iter:                 4000
  n_iter:                   2000
  max_greedy_iter:          4000

  # If true, compute a single global mean/std from TRAINING data only, and normalize
  # all training/testing trajectories using these values.
  normalize:                true

  device:                   'cuda:0'

  noise_ratio:              0.0
  First_Order_Weak:       
    lr:                     0.001
    gradient_clip:          10.0        # Maximum allowable gradient magnitude; will rescale gradients if exceeded.

    # p_rollout grows from p_rollout_init by dp_per_update every rollout_update_freq epochs, capped at max_p_rollout.
    p_rollout_init:         0.0
    rollout_update_freq:    20
    dp_per_update:          0.01
    max_p_rollout:          0.75        # Maximum proportion of the time window used for rollout loss.
    n_rollouts:             8           # Frame-rollout mode: number of rollable start frames to rollout per training parameter per epoch.

    p_IC_rollout_init:      0.01
    IC_rollout_update_freq: 10
    IC_dp_per_update:       0.01
    max_p_IC_rollout:       1.0

    warmup_epochs:          40          # Number of epochs to warmup the learning rate after greedy sampling; checkpointing is disabled during warmup.

    loss_weights:
      recon:                1.0
      rollout:              1.0
      IC_rollout:           0.0

    loss_types:
      recon:                "MSE"
      rollout:              "MSE"
      IC_rollout:           "MSE"
    
workflow:
  use_restart:              False
  restart_file:           

sampler: 
  type:                     'FOM_Rollout'
  FOM_Rollout:
    sample_test_LD:         True            # True: sample LD rollouts; False: use mean LD rollout.
    n_samples:              20              # Required only when sample_test_LD is True.
    normalized_FOM:         True            # Compute absolute errors using normalized or de-normalized values?
    error_normalization:    none            # none | global_std | trajectory_std
    eps:                    0.01

parameter_space:
  parameters:
    - name:                 laser powers
      test_space_type:      file
      file:                 /p/lustre1/robertrs/AM_Agents/Generate_Data/Datasets/5x5x5 dataset/metadata.txt
    - name:                 scan speed
      test_space_type:      file
      file:                 /p/lustre1/robertrs/AM_Agents/Generate_Data/Datasets/5x5x5 dataset/metadata.txt
    - name:                 initial temp
      test_space_type:      file
      file:                 /p/lustre1/robertrs/AM_Agents/Generate_Data/Datasets/5x5x5 dataset/metadata.txt
  test_space:
    type:                   grid

EncoderDecoder:
  type:                     cnn_3d
  trainable:                true
  cnn_3d:
    n_Decoders:             1

    # Fully-connected (FC) part
    hidden_widths_fc:       [1000, 250]
    activations_fc:         ["silu", "silu"]
    latent_dimension:       8

    # Convolutional part (3D)
    conv_channels:          [1, 16, 32, 64]            # Includes input channel.
    conv_kernel_sizes:      3
    conv_strides:           2 
    conv_paddings:          1
    conv_activations:       ["silu", "silu", "silu"]

latent_dynamics:
  interpolator:
    type:                   GP
    GP:
      kernel:
        type:               Matern
        length_scale:       1.0
        length_scale_bounds: [1.0, 1.0e3]
        nu:                 2.5
      constant_value:       1.0
      constant_value_bounds: [1.0e-3, 1.0e3]
      alpha:                4.0e-4
      n_restarts_optimizer: 10
      random_state:         1
  type:                     switch_w
  trainable:                true
  loss_weights: 
    LD:                     20.0
    coef:                   1.0
    stab:                   0.005
  switch_w:
    test_func_type:         'PC-poly'
    test_func_width:        100.0
    overlap:                0.85

physics:
  type:                     Thermal
  Thermal:
    hdf5_dir:               /p/lustre1/robertrs/AM_Agents/Generate_Data/Datasets/5x5x5 dataset/
    use_cnn:                True
    threshold:              1700.0
